# Generated by Django 4.1 on 2022-08-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0002_rename_chip_disabledchip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_in',
            field=models.CharField(default='', max_length=50),
        ),
    ]
