# Generated by Django 4.1 on 2022-08-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0002_rename_chip_disabledchip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disabledchip',
            name='linked_in',
        ),
        migrations.AddField(
            model_name='disabledchip',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='disabledchip',
            name='amount_nf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='disabledchip',
            name='chip_line_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='disabledchip',
            name='chip_plan',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='disabledchip',
            name='cr_gps',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cancelled_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_apn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_company',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_with',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_with_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
