# Generated by Django 4.1 on 2022-08-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0003_alter_disabledchip_linked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_iccid',
            field=models.CharField(default='', max_length=22),
        ),
    ]
