# Generated by Django 4.1 on 2022-08-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0004_disabledchip_add_by_disabledchip_cod_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
