# Generated by Django 4.1 on 2022-08-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0005_alter_disabledchip_linked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disabledchip',
            name='linked_at',
        ),
    ]
