# Generated by Django 4.1 on 2022-08-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0006_remove_disabledchip_linked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabledchip',
            name='linked_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
