# Generated by Django 4.1 on 2022-09-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledchip', '0007_disabledchip_linked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledchip',
            name='add_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='amount_nf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cancelled_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_apn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_company',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_iccid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_line_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_plan',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_with',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='chip_with_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cod_cliente',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='cr_gps',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabledchip',
            name='linked_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
