# Generated by Django 4.1 on 2022-08-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0002_remove_chip_linked_in_chip_add_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='chip_iccid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_with',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
