# Generated by Django 4.1 on 2022-08-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0004_alter_chip_chip_iccid_alter_chip_cod_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='chip',
            name='amount_nf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_line_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_plan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chip',
            name='cr_gps',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
