# Generated by Django 4.1 on 2022-09-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0006_alter_chip_chip_apn_alter_chip_chip_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='amount_nf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='cancelled_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_apn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_company',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_line_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_plan',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_with',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_with_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='cod_cliente',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='cr_gps',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='linked_at',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='linked_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
