# Generated by Django 4.1 on 2022-09-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0007_alter_chip_amount_charged_alter_chip_amount_nf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='add_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
