# Generated by Django 4.1 on 2022-08-21 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChipToConvert',
            fields=[
                ('chip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mb', models.CharField(default='', max_length=22)),
                ('vlrnf', models.CharField(default='', max_length=20)),
                ('X', models.IntegerField(default=0, max_length=20)),
                ('serial', models.IntegerField(default=0)),
                ('localizacao', models.CharField(max_length=50)),
                ('codcliente', models.IntegerField(default=0)),
                ('crgps', models.IntegerField(default=0, max_length=50)),
                ('vlrcobrado', models.CharField(default='', max_length=50)),
                ('forn', models.CharField(default='', max_length=50)),
                ('operadora', models.CharField(max_length=50)),
                ('termino', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('oservico', models.CharField(default='', max_length=50)),
                ('checklinha2148', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
