# Generated by Django 4.1 on 2022-08-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiptoconvert', '0002_alter_chiptoconvert_localizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiptoconvert',
            name='X',
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='checklinha2148',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='codcliente',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='crgps',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='forn',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='localizacao',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='mb',
            field=models.CharField(default='--', max_length=22),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='operadora',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='oservico',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='status',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='termino',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrcobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrnf',
            field=models.CharField(default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='chiptoconvert',
            name='x',
            field=models.IntegerField(default=0),
        ),
    ]
