# Generated by Django 4.1 on 2022-08-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiptoconvert', '0004_alter_chiptoconvert_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiptoconvert',
            name='checklinha2148',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='codcliente',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='crgps',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='forn',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='localizacao',
            field=models.CharField(blank=True, default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='mb',
            field=models.CharField(blank=True, default='--', max_length=22),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='operadora',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='oservico',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='serial',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='status',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='termino',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrcobrado',
            field=models.CharField(blank=True, default='--', max_length=10),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrnf',
            field=models.CharField(blank=True, default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='x',
            field=models.CharField(blank=True, default='--', max_length=200),
        ),
    ]
