# Generated by Django 4.1 on 2022-08-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiptoconvert', '0005_alter_chiptoconvert_checklinha2148_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiptoconvert',
            name='serial',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrcobrado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrnf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='x',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
    ]
