# Generated by Django 4.1 on 2022-08-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiptoconvert', '0006_alter_chiptoconvert_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiptoconvert',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrcobrado',
            field=models.CharField(blank=True, default='--', max_length=10),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='vlrnf',
            field=models.CharField(blank=True, default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='chiptoconvert',
            name='x',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
