# Generated by Django 4.1 on 2022-08-14 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('userLevel', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('set_password', models.CharField(max_length=50)),
            ],
        ),
    ]
